### ISSUE TITLE
How to use this in android project 

### ISSUE THREAD

**Issue by dasbiswajit** [torryharris/Skycons#1]
Hi There,
Its really worth to use in the project. Is there any way to use these in android project.

**Comment by Ninganagouda** [comment]
Hi Dasbiswajit,

We have added a demo project in this library itself. If you want to make use of any icon in your project, you just need to add the icon's widget in the layout xml file.

For example, we you want to use *Moon* icon in the project, then simply add below code in your layout xml file:

```<com.thbs.skycons.library.MoonView
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        app:isStatic = "true"
        app:strokeColor = "#000000"
        app:bgColor = "#ffffff"/>

You can adjust the specs like other Android's native widgets. Same concept applies for all other icons which we have created.
