### ISSUE TITLE
Creating a icon via code

### ISSUE THREAD

**Issue by erikthorselius** [torryharris/Skycons#2]
Hi, do you have any good example how to create a icon from code?
I have problems creating the AttributeSet from my layout. 

    CloudHvRainView cloudHvRainView = new CloudHvRainView(context, attrs);

Don't know if you have any good code example?

**Comment by erikthorselius** [comment]
How come ```CloudFogView``` has ``` public CloudFogView(Context context) {``` but no other view has this constructor?

**Comment by Ninganagouda** [comment]
Hi erikthorselius,

We have now provided the facility to add icon/s through the Java code itself:) 

To add a skycon(For instance, WindView) through Java code, perform following in the activity:

        LinearLayout layout = new LinearLayout(this);
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);
        layout.setLayoutParams(params);

        WindView windView = new WindView(this);
        //Using these params, you can control width & height of the icon
        params.width = 200;
        params.height = 200;
        windView.setLayoutParams(params);

        layout.addView(windView);
        this.setContentView(layout);

**Comment by erikthorselius** [comment]
Thanks alot! I will try it out to night

**Comment by erikthorselius** [comment]
Hi Ninganagouda, more stupid questions :-), any good way to change the colors and static parameter?

**Comment by kudigaracoder** [comment]
Hi,
We're working on this & should have this ready by Monday.

**Comment by erikthorselius** [comment]
No rush for me, my pull request #3 works good enough for me.
